"""empty message

Revision ID: 0da02da59ffc
Revises: 
Create Date: 2021-09-05 00:56:40.759796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da02da59ffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=35), nullable=True),
    sa.Column('user2', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocks')
    # ### end Alembic commands ###
