"""empty message

Revision ID: 13b078769802
Revises: 0da02da59ffc
Create Date: 2021-09-11 22:25:47.902578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b078769802'
down_revision = '0da02da59ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('notification_id', sa.String(length=68), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail', 'notification_id')
    # ### end Alembic commands ###
