"""empty message

Revision ID: 2197c35dfc86
Revises: 72e931d0b815
Create Date: 2021-08-08 00:16:13.527780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2197c35dfc86'
down_revision = '72e931d0b815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('otp_timing', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail', 'otp_timing')
    # ### end Alembic commands ###
