"""empty message

Revision ID: 704f1a5d4c9c
Revises: 2197c35dfc86
Create Date: 2021-08-09 13:46:48.413883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704f1a5d4c9c'
down_revision = '2197c35dfc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('pic', sa.String(length=51), nullable=True))
    op.drop_column('detail', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('date', sa.VARCHAR(length=15), nullable=True))
    op.drop_column('detail', 'pic')
    # ### end Alembic commands ###
