"""empty message

Revision ID: 7ac3019af1d8
Revises: 
Create Date: 2021-08-03 12:04:49.920108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac3019af1d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('date', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('tagline', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=1000), nullable=True),
    sa.Column('msg_type', sa.String(length=5), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('get_user', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('detail')
    # ### end Alembic commands ###
