"""empty message

Revision ID: e2a8dd1dcafc
Revises: 
Create Date: 2021-08-12 14:32:33.000780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a8dd1dcafc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=21), nullable=True),
    sa.Column('pic', sa.String(length=51), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('otp_timing', sa.DateTime(), nullable=True),
    sa.Column('otp', sa.Integer(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=2000), nullable=True),
    sa.Column('msg_type', sa.String(length=6), nullable=True),
    sa.Column('username', sa.String(length=35), nullable=True),
    sa.Column('get_user', sa.String(length=35), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('detail')
    # ### end Alembic commands ###
